EXP:
  NAME: 'iter_net_v11'
MODEL:
  NAME: "IterV11"
  DEVICE: "cuda"
  PARALLEL: False
  DEVICE_IDS: []
DATASET:
  TRAIN: "MNIST"
  VAL: "MNIST"
  TEST: "MNIST"
TRAIN:
  RESUME: True
  # per epoch
  CHECKPOINT_PERIOD: 10
  BATCH_SIZE: 32
  MAX_EPOCHS: 1000
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.0005
  PRINT_EVERY: 100
  VAL_EVERY: 1000
VAL:
  IS_ON: True
  BATCH_SIZE: 128

TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", 'kl', 'bce', 'elbo', 'log_px',
             'mean_grad', 'log_var_grad']
    IMAGE: ['image', 'pred', 'gen']
