# use all encodings
EXP:
  NAME: 'dsprites'
MODEL:
  NAME: "IODINE"
  DEVICE: "cuda"
  PARALLEL: True
  DEVICE_IDS: []
DATASET:
  TRAIN: "DSPRITES"
  VAL: "CLEVR"
  TEST: "CLEVR"
TRAIN:
  RESUME: True
  # per epoch
  CHECKPOINT_PERIOD: 10
  BATCH_SIZE: 32
  MAX_EPOCHS: 1000
  BASE_LR: 3e-4
  WEIGHT_DECAY: 0.0000
  PRINT_EVERY: 20
  VAL_EVERY: 1000
VAL:
  IS_ON: False
  BATCH_SIZE: 128
ARCH:
  ITERS: 5
  SLOTS: 6
  SIGMA: 0.14

  DIM_LATENT: 16
  IMG_SIZE: 64
  IMG_CHANNELS: 3
  LAYERNORM: True
  STOP_GRADIENT: False
  REF:
    CONV_CHAN: 32
    CONV_LAYERS: 3
    MLP_UNITS: 128
    KERNEL_SIZE: 5
  DEC:
    CONV_CHAN: 32
    CONV_LAYERS: 5
    KERNEL_SIZE: 5
  ENCODING: [
    # layer normalized graident of posterior
    'posterior',
    'grad_post',
    # input
    'image',
    # predicted mean
    'means',
    # mask
    'mask',
    # mask logits
    'mask_logits',
    # posterior
    'mask_posterior',
    # gradient of means
    'grad_means',
    # gradient of mask
    'grad_mask',
    # likelihood
    'likelihood',
    # leave-one-out likelihood
    'leave_one_out_likelihood',
    # coordinate channel
    'coordinate'
  ]


TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: [
      "loss", "kl", "likelihood", "var",
      'mean_grad_norm1', 'mean_grad_norm2']
    IMAGE: [
      'image', 'pred', 'gen',
      'mask_0', 'mask_1', 'mask_2','mask_3', 'mask_4','mask_5','mask_6',
      'pred_0', 'pred_1', 'pred_2','pred_3', 'pred_4','pred_5','pred_6',
      ]
