EXP:
  NAME: 'iodine_dua'
MODEL:
  NAME: "IODINE"
  DEVICE: "cuda"
  PARALLEL: True
  DEVICE_IDS: []
DATASET:
  TRAIN: "CLEVR"
  VAL: "MNIST"
  TEST: "MNIST"
TRAIN:
  RESUME: True
  # per epoch
  CHECKPOINT_PERIOD: 10
  BATCH_SIZE: 32
  MAX_EPOCHS: 1000
  BASE_LR: 3e-4
  WEIGHT_DECAY: 0.0005
  PRINT_EVERY: 20
  VAL_EVERY: 1000
VAL:
  IS_ON: False
  BATCH_SIZE: 128

TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", "kl", "likelihood", "var"]
    IMAGE: ['image', 'pred', 'gen',
            'mask_0', 'mask_1', 'mask_2','mask_3', 'mask_4','mask_5','mask_6',
    'pred_0', 'pred_1', 'pred_2','pred_3', 'pred_4','pred_5','pred_6']
