# use all encodings
EXP:
  NAME: 'iodine_all'
MODEL:
  NAME: "IODINE"
  DEVICE: "cuda"
  PARALLEL: True
  DEVICE_IDS: []
DATASET:
  TRAIN: "CLEVR"
  VAL: "CLEVR"
  TEST: "CLEVR"
TRAIN:
  RESUME: True
  # per epoch
  CHECKPOINT_PERIOD: 10
  BATCH_SIZE: 32
  MAX_EPOCHS: 1000
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.0005
  PRINT_EVERY: 20
  VAL_EVERY: 1000
VAL:
  IS_ON: False
  BATCH_SIZE: 128
ARCH:
  ITERS: 5
  SLOTS: 7
  SIGMA: 0.13
  DIM_LATENT: 128
  IMG_SIZE: 32
  IMG_CHANNELS: 3
  LAYERNORM: True
  STOP_GRADIENT: False
  REF:
    CONV_CHAN: 64
    MLP_UNITS: 256
  DEC:
    CONV_CHAN: 64
  ENCODING: [
    # input
    'image',
    # layer normalized graident of posterior
    'grad_post',
    # predicted means
    'means',
    # mask
    'mask',
    # mask logits
    'mask_logits',
    # gradient of means
    'grad_means',
    # gradient of mask
    'grad_mask',
    # posterior
    'posterior',
    # mask posterior
    'mask_posterior',
    # likelihood
    'likelihood',
    # leave-one-out likelihood
    'leave_one_out_likelihood',
  ]


TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: [
      "loss", "kl", "likelihood", "var",
      'mean_grad_norm1', 'mean_grad_norm2']
    IMAGE: [
      'image', 'pred', 'gen',
      'mask_0', 'mask_1', 'mask_2','mask_3', 'mask_4','mask_5','mask_6',
      'pred_0', 'pred_1', 'pred_2','pred_3', 'pred_4','pred_5','pred_6',
      ]
