# use all encodings
EXP:
  NAME: 'iodine__slot_11__sigma__0.18'
MODEL:
  NAME: "IODINE"
  DEVICE: "cuda"
  PARALLEL: False
  DEVICE_IDS: []
DATASET:
  TRAIN: "OBJ3D"
  VAL: "OBJ3D"
  TEST: "OBJ3D"
  DATA_DIR: "/data/public/rw/yifu/oomba_3d/7_objects_2019-13_a"
TRAIN:
  RESUME: True
  # per epoch
  CHECKPOINT_PERIOD: 10
  BATCH_SIZE: 13
  MAX_EPOCHS: 1000
  BASE_LR: 3e-4
  WEIGHT_DECAY: 0.0000
  PRINT_EVERY: 20
  VAL_EVERY: 1000
VAL:
  IS_ON: False
  BATCH_SIZE: 13
ARCH:
  ITERS: 5
  SLOTS: 11
  SIGMA: 0.18

  DIM_LATENT: 64
  IMG_SIZE: 128
  IMG_CHANNELS: 3
  LAYERNORM: True
  STOP_GRADIENT: False
  REF:
    CONV_CHAN: 64
    CONV_LAYERS: 4
    MLP_UNITS: 256
    KERNEL_SIZE: 3
    STRIDE: 2
  DEC:
    CONV_CHAN: 64
    CONV_LAYERS: 4
    KERNEL_SIZE: 3
  ENCODING: [
    # layer normalized graident of posterior
    'posterior',
    'grad_post',
    # input
    'image',
    # predicted mean
    'means',
    # mask
    'mask',
    # mask logits
    'mask_logits',
    # posterior
    'mask_posterior',
    # gradient of means
    'grad_means',
    # gradient of mask
    'grad_mask',
    # likelihood
    'likelihood',
    # leave-one-out likelihood
    'leave_one_out_likelihood',
    # coordinate channel
    'coordinate'
  ]


TENSORBOARD:
  LOG_DIR: "/data/private/tensorboard/"
  IS_ON: True
  TARGETS:
    SCALAR: [
      "loss",
      "kl",
      "likelihood",
      "time_per_iteration",
      "med_time_per_iteration"
      ]
    IMAGE: [
      'train_grid',
      'val_grid',
      ]
